site_name: Db2 Click to Containerize
theme:
  name: material
nav:
  - Introduction: "index.md"
  - Pre-Requisites: "prerequisites.md"
  - Installation: "installation.md"
  - User Interface Overview: "gui.md"
  - Authentication:
    - SSH Authentication: "ssh.md"
    - Cluster Authentication: "cluster.md"
  - Command Line:
    - Db2 Shift Syntax: "syntax.md"
    - Options Reference: "reference.md"
  - Shift Scenarios:
    - Scenario Overview: "scenarios.md"
    - Db2 Shift to Pod: "shiftpod.md"
    - Db2 Shift to Instance: "shiftinstance.md"
    - Clone a Database: "clone.md"
    - Deploy a Clone to a Pod: "deploypod.md"
    - Deploy a Clone to an Instance: "deployinstance.md"
    - HADR Setup Instance to Pod: "hadrpod.md"
    - HADR Setup Instance to Instance: "hadrinstance.md"  
    - LDAP and DMC Initialization: "ldapdmc.md"
    - Clone Copying: "clonecopy.md"
  - Best Practices: "bestpractices.md"
  - Reference:
    - Options Reference: "reference.md"
    - Support: "support.md"
  - Disclaimer: "disclaimer.md"
